# -*- coding: utf-8 -*-
"""image_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDhKvFYzl8Q7sSufbRelPGx2gHewo7cy
"""

from diffusers import StableDiffusionPipeline
import torch

# Load Stable Diffusion model
pipeline = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")

# Set to GPU if available, otherwise CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
pipeline.to(device)

# Text prompt for generating images
prompt = "a serene sunset over a futuristic city"

# Generate 3 images
for i in range(1, 4):
    image = pipeline(prompt).images[0]
    image.save(f"generated_image_{i}.png")
    print(f"Image {i} saved as 'generated_image_{i}.png'")