# -*- coding: utf-8 -*-
"""image_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwO2LOH6D5eu8qU8plcGE5qvz75jh7S7
"""

import torch
from torchvision import transforms
from PIL import Image

# Define image preprocessing steps
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

# Preprocess each image
for i in range(1, 2):
    image = Image.open(f"generated_image_{i}.png")
    tensor_image = transform(image)

    # Save the tensor as a .pt file
    torch.save(tensor_image, f"preprocessed_image_{i}.pt")
    print(f"Image {i} preprocessed and saved as 'preprocessed_image_{i}.pt'")